on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix_build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Build glxgears
        run: nix build .#glxgears
      - name: Build glxinfo
        run: nix build .#glxinfo
